// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4fl3FY3Osoo4elK6_5bQpmaUgyKX_2F0',
    appId: '1:829680860693:web:2b67f435201e9314ac981c',
    messagingSenderId: '829680860693',
    projectId: 'olxad-507e6',
    authDomain: 'olxad-507e6.firebaseapp.com',
    storageBucket: 'olxad-507e6.firebasestorage.app',
    measurementId: 'G-PNMMR614VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8nN45ZcYxgnL5HnZUNESjy-mnACPLYuk',
    appId: '1:829680860693:android:561f3838e04cbd8eac981c',
    messagingSenderId: '829680860693',
    projectId: 'olxad-507e6',
    storageBucket: 'olxad-507e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ9P87ZXX4_t2TpBWxyeQUIEtqknKi2Kg',
    appId: '1:829680860693:ios:db61f4f5d65e643aac981c',
    messagingSenderId: '829680860693',
    projectId: 'olxad-507e6',
    storageBucket: 'olxad-507e6.firebasestorage.app',
    androidClientId: '829680860693-jo62jmd623fcj0k3i16utk7j1q60fvj4.apps.googleusercontent.com',
    iosClientId: '829680860693-a1veuonmksrjdrk542pp8hr1idjkmpbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ9P87ZXX4_t2TpBWxyeQUIEtqknKi2Kg',
    appId: '1:829680860693:ios:db61f4f5d65e643aac981c',
    messagingSenderId: '829680860693',
    projectId: 'olxad-507e6',
    storageBucket: 'olxad-507e6.firebasestorage.app',
    androidClientId: '829680860693-jo62jmd623fcj0k3i16utk7j1q60fvj4.apps.googleusercontent.com',
    iosClientId: '829680860693-a1veuonmksrjdrk542pp8hr1idjkmpbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.olxad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4fl3FY3Osoo4elK6_5bQpmaUgyKX_2F0',
    appId: '1:829680860693:web:231385d1d814d789ac981c',
    messagingSenderId: '829680860693',
    projectId: 'olxad-507e6',
    authDomain: 'olxad-507e6.firebaseapp.com',
    storageBucket: 'olxad-507e6.firebasestorage.app',
    measurementId: 'G-2NNTCCZPYG',
  );

}