import 'package:bloc/bloc.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:olxad/bloc/auth/auth_even.dart';
import 'package:olxad/bloc/auth/auth_state.dart';
import 'package:olxad/model/user_data.dart';
import 'package:google_sign_in/google_sign_in.dart';

class RegestrationBloc extends Bloc<RegestrationEvent, RegestrationState> {
  final GoogleSignIn googleSignIn = GoogleSignIn.instance;

  RegestrationBloc() : super(RegestrationInitial()) {
    on<Submmited>((event, emit) async {
      emit(RegestrationLoading());
      try {
        final userCredential = await FirebaseAuth.instance
            .createUserWithEmailAndPassword(
                email: event.email, password: event.password);
        if (userCredential.user == null) {
          throw Exception('User creation failed: User is null');
        }
        final userDetails = UserDetails(
          uid: userCredential
              .user!.uid, // Get the unique ID generated by Firebase
          location: '', // Default empty location
          email: userCredential.user!.email ??
              event.email, // Use Firebase email, or fallback to input
        );
        await FirebaseFirestore.instance
            .collection('/users') // Go to 'users' folder
            .doc(userDetails.uid) // Find the file with this User ID
            .set(userDetails.toJson()); // Write the JSON data

        emit(RegestrationSuccess());
      } on FirebaseAuthException catch (e) {
        // Handle specific Firebase errors
        String message = 'Registration failed';
        if (e.code == 'weak-password') {
          message = 'The password provided is too weak.';
        } else if (e.code == 'email-already-in-use') {
          message = 'The account already exists for that email.';
        }
        emit(RegestrationFailure(error: message));
      } catch (e) {
        // Handle generic errors
        emit(RegestrationFailure(error: e.toString()));
      }
    });
    on<GoogleSignIN>((event, emit) async {
      emit(RegestrationLoading());
      try {
        await googleSignIn.initialize();
        // Step 3: Authenticate user (open Google account chooser)
        final googleSignInAccount = await googleSignIn.authenticate();

        // Step 5: Get authentication tokens from Google
        final googleAuth = googleSignInAccount.authentication;
        // Step 6: Create Firebase credential using Google token
        final credential = GoogleAuthProvider.credential(
          idToken: googleAuth.idToken,
        );
        final firebaseAuth = FirebaseAuth.instance;
        await firebaseAuth.signInWithCredential(credential);
        final user = firebaseAuth.currentUser;
        if (user != null) {
          final userDetais = UserDetails(
            uid: user.uid,
            email: user.email,
          );
          await _storeUserData(userDetails: userDetais);
        }
        emit(RegestrationSuccess());
      } catch (e) {
        emit(RegestrationFailure(error: e.toString()));
      }
    });
    on<LoginSubmitted>((event, emit) async {
      emit(RegestrationLoading());
      try {
        final firebaseAuth = FirebaseAuth.instance;
        await firebaseAuth.signInWithEmailAndPassword(
          email: event.email,
          password: event.password,
        );
        emit(RegestrationSuccess());
      } on FirebaseAuthException catch (e) {
        String message = 'Login failed';
        if (e.code == 'user-not-found') {
          message = 'No user found for that email.';
        } else if (e.code == 'wrong-password') {
          message = 'Wrong password provided.';
        } else if (e.code == 'invalid-credential') {
          message = 'Invalid email or password.';
        }
        emit(RegestrationFailure(error: message));
      } catch (e) {
        emit(RegestrationFailure(error: e.toString()));
      }
    });
  }
  Future<void> _storeUserData({
    required UserDetails userDetails,
  }) async {
    final firestore = FirebaseFirestore.instance;
    await firestore
        .collection('/users')
        .doc(userDetails.uid)
        .set(userDetails.toJson());
  }
}
